[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
# Un thème futuriste et ésotérique
primaryColor = "#7000ff"  # Violet/pourpre cosmique
backgroundColor = "#030723"  # Bleu nuit profond
secondaryBackgroundColor = "#0c1222"  # Légèrement plus clair que le fond
textColor = "#e4eaff"  # Blanc bleuté
font = "sans serif"